highspirit7/section1-15.js
`단어 길이가 짝수일 때는 가운데 2개 숫자 출력`
단어길이가 홀수 일 때는 2로 나눈 결과를 내림 처리하였습니다.(문자열도 index는 0부터 시작하니까요)
단어길이가 짝수 일 때는 2로 나눈 결과 그리고 그 결과에서 1을 뺀 숫자들을 index로 사용하여 가운데 2개 숫자로 가져오도록 하였습니다.
=> [이지열]1-15.가운데 문자 출력

highspirit7/section1-14.js
정답용 변수 하나와 가장 긴 문자열의 길이를 담을 변수(maxLength) 하나를 각각 선언.
for문으로 주어진 배열을 순회하면서 각 요소(단어)의 길이와 maxLength를 비교하여 
단어 길이가 maxLength보다 클 경우 위 두 변수를 업데이트.
=> [이지열] 1-14.가장 긴 문자열

highspirit7/section1-17.js
빈 배열 하나(중복되지 않는 단어들을 담기 위한)를 만든 다음 
for문으로 매개변수로 받은 배열은 순회하면서 해당 배열에 없는 단어이면 추가한다.(이를 판별할 때 every 메소드 사용)
그리고 중복되지 않는게 판별되어서 해당 배열에 추가할 때 console.log로 출력도 함께 해준다.
=> [이지열] 1-17.중복단어제거

highspirit7/section1-8.js
처음에는 9 난쟁이 키 데이터 중 7개를 뽑아서 합을 구해서 100이 되는 경우를 찾아야 하나 싶었습니다. (삽질 중..) 
그런데 그게 비효율적일 것 같아서 9 난장이 중 2명을 선택해서 판별해보면 되겠다는 결론에 이르렀습니다.
9개 데이터중 2가지를 순차적으로 선택하기 위해 for문을 중첩하여 사용했습니다.
배열 기본 내장 함수중 하나인 reduce를 사용하여 9명 난장이 전체의 키 데이터 합을 구하였습니다. 
그래서 이중 for문으로 선택된 두 명의 키 데이터를 그 합에서 차감하여 100이 되는지 확인하도록 하였습니다.
=> [이지열] 1-8.일곱난쟁이

goawmfhfl/1_8.js
- 아홉 난장이 중에서 일곱 난장이를 찾아내자!
- for of 문을 활용
```jsx
var myFish = ['angel', 'clown', 'drum', 'mandarin', 'sturgeon'];
var removed = myFish.splice(3, 1);
// removed is ["mandarin"]
// myFish is ["angel", "clown", "drum", "sturgeon"]
```
- splice() 메서드는 배열의 기존 요소를 삭제 또는 교체하거나 새 요소를 추가하여 배열의 내용을 변경한다
- push() 메서드는 배열의 끝에 하나 이상의 요소를 추가하고, 배열의 새로운 길이를 반환한다
=> [최재영] 1_8 일곱난장이

goawmfhfl/goawmfhfl_1_10.js
=> [최재영] 1_10 문자찾기

goawmfhfl/goawmfhfl_1_13.js
- 전달받은 문자열 중 대문자는 소문자로 소문자는 대문자로 바꾸자
- `toLowerCase()` 메서드는 문자열을 소문자로 변환해 반환합니다.
- `toUpperCase()` 메서드는 문자열을 대문자로 변환해 반환합니다.
- `charCodeAt()` 메서드는 주어진 인덱스에 대한 UTF-16 코드를 나타내는 0부터 65535 사이의 정수를 반환합니다.
`String.fromCharCode()` 메서드는 UTF-16 코드 유닛의 시퀀스로부터 문자열을 생성해 반환합니다.
- 65 ~ 90 대문자
- 97 ~ 122 소문자
- 대문자 +32 = 소문자
- 소문자 -32 = 대문자
=> [최재영] 1_13 대소문자변환

goawmfhfl/goawmfhfl.1_14.js
- 전달받은 문자열중 가장 긴 문자열을 찾아라
- `Number.MIN_SAFE_INTEGER` 상수는 JavaScript에서 안전한 최대 정수값을 나타냅니다. (253 - 1).
=> [최재영] 1_14 가장 긴 문자열

goawmfhfl/goawmfhfl_1_15.js
- 전달받은 문자열 중 가운데 문자열을 출력하라
- `substring()메소드`는 string 객체의 시작 인덱스로 부터 종료 인덱스 전 까지 문자열의 부분 문자열을 반환합니다.
- 홀수 일 경우 substring(mid, mid+1)
```jsx
let str = "event"
console.log('answer :', str.substring(mid,mid+1)); // e 출력
```
- 짝수 일 경우 substring(mid-1, mid+1)
```jsx
let str = "node"
console.log('answer :', str.substring(mid-1,mid+1)); // od 출력
```
- `Math.floor()` 함수는 주어진 숫자와 같거나 작은 정수 중에서 가장 큰 수를 반환합니다.
=> [최재영] 1_15 가운데 문자 출력

goawmfhfl/goawmfhfl_1_16.js
- 전달받은 문자열 중 중복되는 문자를 제거하자
- **`indexOf()`** 메서드는 호출한 String 객체에서 주어진 값과 일치하는 첫 번째 인덱스를 반환합니다. 일치하는 값이 없으면 -1을 반환합니다.
```jsx
let str = "kyochonchicken"
console.log(str.indexOf('k')); // 0 출력
console.log(str.indexOf('c',4)); // 7 출력
console.log(str.indexOf('m')); // -1 출력
```
=> [최재영] 1_16 중복문자제거

goawmfhfl/goawmfhfl_1_17.js
- 전달받은 배열의 원소중 중복되는 문자를 제거해라
- **`indexOf()`** 메서드는 호출한 String 객체에서 주어진 값과 일치하는 첫 번째 인덱스를 반환합니다. 일치하는 값이 없으면 -1을 반환합니다.
```jsx
let str = "kyochonchicken"
console.log(str.indexOf('k')); // 0 출력
console.log(str.indexOf('c',4)); // 7 출력
console.log(str.indexOf('m')); // -1 출력
```
- `filter()` 메서드는 주어진 함수의 테스트를 통과하는 모든 요소를 모아 새로운 배열로 반환합니다.
```jsx
answer = s.filter((v,i)=>{
return s.indexOf(v)===i
})
```
- v = `value` 즉, ["good","time","good","time","student"]
- i = `index` 즉 value의 index 0 1 2 3 4
=> [최재영] 1_17 중복단어제거

index.html, tiaz0128/1_1.js, tiaz0128/1_8.js
- 두개 의 포인터 값 i, j 를 이용하여 전체 배열의 합에서 두개의 값을 뺴서 100이 나오는 경우
- 이 경우에 두개의 포인터 값 i, j 의 값이 제거 배열에서 제외 시켜야 하는 값이다.
- 배열에서 특정한 부분을 제거 하기 위해서 splice( ) 메소드를 사용
- 첫번째 인자 부터 두번째 인자값 만큼 해당 요소를 제거 한다.
```js
Array.splice(start: number, deleteCount?: number):
```
=> [통붕이] 1_8 일곱 난쟁이

tiaz0128/1_10.js
```js
String.split('구분자')
```
- 해당하는 구분자로 문자열을 나눠서 배열형태로 만들어 준다.
- 시작과 마지막에 구분자 문자가 있는 경우에는 빈 문자열이 하나 추가 된다. (기억하자!)
- 구분자 뒤에 올수 있는 문자가 없는 경우에도 빈 문자열이 추가된다.
=> [통붕이] 1_10 문자 찾기

tiaz0128/1_14.js
- 처음 부터 두개의 문자열을 계속 비교하면서 가장 긴 length 값을 찾는 형태로 구현
- 두 개의 문자열을 비교하여 긴 문자열을 다시 reduce 의 return 으로 돌려주면 해당 문자열이 다음 회차에 prev 로 전달 된다.
```js
arr.reduce((prev, next)=> { 
return prev.length > next.length ? prev : next
}, '')
```
=> [통붕이] 1_14 가장 긴 문자열

sonsurim/1_10.js
- 약 6분
```
s1: 약 0.033초
s2: 약 0.04초
s3: 약 0.031초
```
**`s3` > `s1` > `s2`**
- `split`으로 배열 생성 후, 기본 `for`문을 이용한 `s3`가 가장 빠름 (환경에 따라 차이가 있을 수 있습니다.)
- 정규표현식이 느리다고 알고 있었는데 생각보다 차이가 얼마나지 않아서 신기했습니다.
- `for...of`문의 실행 속도가 의외로 반전이었습니다.
- 실행 환경에 따라 차이가 있겠지만 시간 체크 해보는 것도 좋은 것 같습니다!
- `split`에 매개변수를 구분점으로 이용하는 방법은 생각 못했습니다.. 이 부분이 아쉬웠습니다!
=> [손수림] 1_10 문자 찾기

sonsurim/1_11.js
- 약 3분 30초
```
s1: 약 0.04초
s2: 약 0.09초
```
- `s1` > `s2`
- `split`말고 다른 내장 함수를 이용해서 풀어보고 싶었는데 또 `split`을 사용했습니다 ㅎㅎ..
- `for...of`문을 이용했을 때 해당 아이템과 아이템이 대문자인지를 판별하는 방법을 몰라서 `for`를 사용했는데 강사님 말씀들어보니 아래와 같이 할 수 있었습니다..!
```
for(let i of arr) {
if (i === i.toUpperCase())
}
```
- `arr[i]` === `i` 라는 점을 생각해서 풀었으면 더 좋았을 것 같습니다.
- 다른 분이 정규 `표현식, match, for...of`를 이용해서 푸신 것을 보고 `match`로만 풀어보았습니다.
- 코드의 간결함은 정규표현식과 `match`를 활용한 것이 압도적으로 좋았는데 생각보다 실행 속도의 차이가 있어서 신기했습니다!
- `통붕이`님께서 `match` 사용에 대해 조언해주셨다!
> 만약에 매치되는 경우가 없는 경우에는 어떻게 동작 할 지도 한번 테스트 해보시면 좋을 듯 합니다!.
- 또 생각치도 못한 오류였습니다.. 🤦‍♀️
- 지열님의 코드 `s.match(/[A-Z]/g)?.length`에서 `match`뒤의 `?`가 `옵셔널 체이닝`인지 모르고 오타인줄 알고 오타있다고 코멘트 남겼었다^^^^^... ㅋㅋㅋ 뒤늦게 알게되고 진짜 너무 창피했어욬ㅋㅋㅋㅠㅠㅠ
- 통붕이님의 세심한 피드백과 멤버들의 다양한 풀이 덕분에 좀 더 다양한 시각으로 코드를 바라보게 되는 것 같습니다! ㅎㅎ 알통 최고 💪
=> [손수림] 1_11 대문자 찾기

sonsurim/1_12.js
- 약 1분
```
약 0.03초
```
- 내장 함수를 사용하니 문제를 빨리 풀 수 있었습니다.
- 내장 함수 외에 for ...of문을 이용하니 시간이 약 0.035초 정도 나왔습니다.
- 아스키코드를 이용한 로직은 약 0.04초가 나왔습니다.
=> [손수림] 1_12 대문자로 통일

sonsurim/1_14.js
- 약 5분 30초
```
약 0.035초
```
- `filter` 함수를 사용해보려 했는데 실패했습니다..ㅎㅎ
- `forEach`문으로 우선 구현해보는걸로,, ㅎㅅㅎ..
=> [손수림] 1_14 가장 긴 문자열

sonsurim/1_15.js
- 약 8분
```
약 0.033초
```
- 이 기회에 `substr`과 `substring` 차이점에 대해 생각해볼 수 있었습니다.
- 한개의 연산만 이용해서 `mid`를 두고 `mid`에서 -1로 활용하는 방식이 현재 코드보다 더 좋은 것 같습니다!
```
let mid = Math.floor(s.length/2);
//홀수
s.substr(mid,1);
// 짝수
s.substrt(mid-1, 2);
```
=> [손수림] 1_15 가운데 문자 출력

goawmfhfl/goawmfhfl_1_9.js
- 전달받은 문자열 A를 #으로 바꾸자
- `for...of 명령문`은 반복가능한 객체에 대해서 반복하고 각 개별 속성값에 대해 실행되는 문이 있는 사용자 정의 반복 후크를 호출하는 루프를 생성합니다.
=> [최재영] 1_9 A를 #으로

wj2kim/1_10.js
/**
* 접근 방법 
* 
* 1. 특정문자가 문자열에 몇개 존재하는지 알아낼려면 문자열의 
*    문자와 특정 문자를 무조건 한번씩은 비교할 수 밖에 없겠다는 생각이 들었다.
* 2. 한번씩 비교하면 되기 때문에 for문을 사용해야겠다.
*/
=> [김우정] 1_10 문자 찾기

sonsurim/1_17.js
- 약 2분
```
약 0.03초
```
- `set`을 알고있어서 중복 문자에 대한 처리를 빠르게 풀 수 있었습니다.
- `set` 이라는 자료구조에 대한 근본적인 지식은 많이 부족한 것 같다고 느꼈습니다!
- 자바스크립트에서의 자료구조에대한 의미가 무엇인지...이 부분에 대해 더 생각을 해봐야할 것 같습니다.
=> [손수림] 1_17 중복단어제거

index.html, wj2kim/1_9.js
/**
* 접근 방법 
* 
* 1. 보자마자 ES2021 스펙에 추가되는 String.replaceAll 함수가 생각났다.
* 2. String을 split("") 하여 array로 만들고 map() iterate하면서 'A' 일때, 
*    해당 값을 '#'으로 바꿔서 새로운 array를 만들어 string으로 바꿔주면 해결 할 수 있을것 같다.
* 3. 정규표현식을 사용해서 replace 시켜주는 방법으로도 해결 할 수 있을것 같다. 
* 4. 그냥 간편하게 1번 방법으로 풀자.
*/
=> [김우정] 1_9 A를#으로 

index.html, tiaz0128/1_9.js
- 문자열 하나 또는 여러개를 변경 가능
- 여러개를 변경 하기 위해서는 정규표현식의 `g` 플레그를 사용
- [replace - MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/replace)
```js
var newStr = str.replace(regexp|substr, newSubstr|function)
```
- 다양한 방식으로 이용 가능하다.
- 정규표현식을 사용하는 경우에는 반드시 `g` 플레그 를 붙여 주어야 TypeError 가 발생하지 않는다.
- [replaceAll - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)
```js
replaceAll(regexp, newSubstr)
replaceAll(regexp, replacerFunction)
replaceAll(substr, newSubstr)
replaceAll(substr, replacerFunction)
```
=> [통붕이] 1_9 A를 #으로

index.html, wj2kim/1_8.js
/**
* 접근 방법
* 
* 1. 무조건 7개의 숫자를 출력 
* 2. 합은 max 100
* 3. 입력된 순서대로 키를 출력 -> 앞에서 부터 누적해야 함
* 4. 그렇다면 뒤에서 부터 2개를 빼도 되지 않을까 하는 생각이 들었다
* 5. 뒤에서 부터 2개의 합 > 총합 - 100 이면 그 둘이 가짜 난쟁이
* 6. 뒤에서 부터 2개를 빼면 반복도 줄어들 뿐만 아니라 array 자료구조에서 숫자를 제거할때도 더 효율적일 것 같다. 
* 
*/
/**
* 아쉬운 점 
* 
* spread operator로 candidates를 얕게 복사했는데 이 비용이 얼마나 들지 잘 모르겠다
* 빈 배열을 선언하고 하나씩 채워가는게 더 효율적일수도 있겠다는 생각도 들었다.
* for 한번으로 끝내고 싶었는데 무조건 이중 for문을 사용할 수 밖에 없었다. 
* 이중 for문을 바로 빠져나오는 방법이 label 밖에 생각이 안났다.
*/
/**
* for fun 
* 
* for, for..of, forEach, map, reduce Performance test
* https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/
* https://betterprogramming.pub/which-is-the-fastest-while-for-foreach-for-of-9022902be15e
* https://levelup.gitconnected.com/which-is-faster-for-for-of-foreach-loops-in-javascript-18dbd9ffbca9 …
=> [김우정]1_8 일곱난쟁이

wj2kim/1_12.js
/**
* 접근 방법 
* 
* 1. 자바스크립트 String Prototype 메소드인 toUpperCase 를 사용하면 매우 간단하게 풀 수 있는 문제이다.
* 2. 1_11 강의에서 배운 charCodeAt을 응용해보기 - 반복문을 돌면서 소문자 일때 대문자로 바꿔주자 
* 3. 대문자로 바꿀때 toUpperCse 메소드를 사용하면 반복문을 도는 의미가 없으니 다른 방식으로 바꿔보자 
* 4. String Prototype의 fromCharCode() 메소드를 통해 아스키 넘버를 인자로 주면 코드에 맞는 아스키 유닛을 string으로 넘겨준다고 한다. 
* 5. 대문자에서 소문자는 +32 의 규칙이 있으니 이용해보자 
* 6. ASCII 코드 소문자는 97번 부터 122번까지다.
*/
=> [김우정] 1_12 대문자로 통일

wj2kim/1_13.js
/**
* 접근 방법 
* 
* 1. 1_12 와 매우 비슷한 방식으로 풀면 될것 같다. 
* 2. 반복문을 통해 대문자는 -32, 소문자는 +32 로 string 을 새로 만들어 반환하도록 만들면 되겠다.
* 3. ASCII 코드 대문자는 65번부터 90번까지고 소문자는 97번 부터 122번까지다.
*/
=> [김우정] 1_13 대소문자변환

wj2kim/1_14.js
/**
* 접근 방법 
* 
* 1. 문자열의 길이는 서로 다르기 떄문에 정답은 무조건 하나이다.
* 2. 문자열이기 때문에 문자열인지 확인하는 절차가 필요하다.
* 3. 반복문과 함께 String.prototype의 length 메소드를 사용하면 쉽게 해결 할 수 있다.
*/
=> [김우정] 1_14 가장 긴 문자열

highspirit7/2_1.html, highspirit7/2_2.html, highspirit7/2_3.html, highspirit7/2_4.html, highspirit7/2_5.html, highspirit7/2_6.html, highspirit7/2_7.html
Nullish coalescing operator 및 filter 메소드 활용
반복문을 돌면서 제일 큰 키 데이터를 지속적으로 저장하고 제일 큰 키 데이터보다 큰 경우 카운팅
A와 B가 낸 것의 합을 이용해서 로직 구성
JSON 관련 메소드 사용하서 깊은 복사로 원본 배열 유지
sort 및 indexOf 메소드 활용
각 행의 합, 각 열의 합, 두 대각선의 합을 순서대로 계산.
각 행의 합 계산 후 최대합 데이터 업데이트
각 열의 합 계산 후 최대합 데이터 업데이트
각 대각선의 합 계산 후 최대합 데이터 업데이트
> 아쉬운 점 : 합 데이터들 배열에 모아놓고 Math.max 이런 메소드로 한 번에 계산하는게 더 깔끔할 것 같습니다..
이중 for문을 돌면서 동서남북 방향의 높이를 계산하고 비교하여 봉우리가 맞을 경우 카운팅.
---
여력이 없어서 강의에서의 솔류션을 보지 못하고 그냥 제 생각대로만 풀어본 방식입니다. 그래서 다른 분들과 좀 더 다르고 그럴 수도 있을 것 같네요. 한 문제(점수계산)는 설명을 어떻게 해야할지 잘 몰라서 스킵했습니다 양해부탁드려요ㅠㅠ
=> [이지열] lesson 2

goawmfhfl/2.1.js, goawmfhfl/2.2.js, goawmfhfl/2.3.js, goawmfhfl/2.4.js, goawmfhfl/2.5.js, goawmfhfl/2.6.js, goawmfhfl/2.7.js
> # *2-1 큰 수 출력하기*
- 포문을 활용해서 다음 조건문에서 인덱스의 요소와 이전 인덱스 요소의 값을 비교하자.
- 이중 포문을 활용해야하나??  → 불가
- reduce를 활용해서 풀 수 있는 방법이 있을까? → 가장 긴 문자열에서는 가능했지만 이 문제에서는 잘 모르겠다.
- reduce 재도전 → 성공
- 이중  포문으로 풀면 더 어렵게 풀어야 하는 문제였음..
- [7,9,6,12]가 정답으로 나왔어야 하는데 [9,6,12]만 정답으로 나오는 상황에서 헤매었음
- 문제를 제대로 안 읽음 첫 번째 수는 무조건 출력한다는 조건을 제대로 못봄.
- reduce() 메서드를 활용해서 문제를 풀어봤음
- 문제를 잘 읽자 !
> # *2-2 보이는 학생 수*
- 맨 앞의 학생은 보일 수 밖에 없다
- for문을 통해서 앞의 학생의 키와 뒤의 학생의 키를 비교해야 할 것 같다.
- max를 활용해서 유동적으로 값을 비교해줄 생각을 하지 못했다.
- MIN.SAFE.INTERGER을 통한 안전한 상수 값을 구했다.
- for 문을 통해서 원소들을 순회하며 조건문에 맞는 값을 answer에 카운팅 해 주었다.
> # *2-3 가위 바위 보*
- 이기는 경우와 지는 경우를 모두 생각해 봐야 할 것 같다.
- if else문을 활용하면 될 것 같다. if문에는 이기는 경우와 비기는 경우만을 출력
else문에는 그 외의 상황일 경우 즉 지는 경우 출력
```jsx
for(let i=0; i<A.length; i++){
if(A[i] === 1 && B[i] === 3) answer.push("A") 
else if …
```
=> [최재영] lesson2
